force-app/main/default/objects/Shelter__c/Shelter__c.object-meta.xml
<CustomObject>
    
    <label>Shelter</label>
    <nameField>
        <label>Shelter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shelters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shelter__c/fields/Time_Opened__c.field-meta.xml
<CustomField>
    <fullName>Time_Opened__c</fullName>
    <label>Time Opened</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HoursController.cls
public with sharing class HoursController {
    @AuraEnabled(Cacheable=true)
    public static String showHours(String shelterID) {
        List<Shelter__c> shelter = [select Time_Opened__c from Shelter__c where Id =: shelterID];
        if(shelter == null) {
            return null;
        }
        Shelter__c record = shelter[0];
        if(record.Time_Opened__c == null)
            return null;
        return record.Time_Opened__c;
    }
}